/**
 * @file plot_engine.js
 * @description
 * This is the core of the Auto Plot Engine. It orchestrates the process of
 * fetching the current world state, calling a secondary AI to generate a 
 * plot outline, and then injecting that outline into a dedicated lorebook.
 */

import { getAllContext } from './information_aggregator.js';
import { getSettings } from './settingsManager.js';
import { loadWorldInfo, createNewWorldInfo, saveWorldInfo, world_names, createWorldInfoEntry } from "/scripts/world-info.js";
import { eventSource, event_types } from "/script.js";
import { plotLogger, apiLogger } from './logger.js';

const { toastr, TavernHelper } = window;

const ENTRY_COMMENT = "自动剧情大纲";

/**
 * Updates the dedicated lorebook with the new plot outline.
 * Creates the lorebook and entry if they don't exist.
 * @param {string} outlineContent - The plot outline generated by the AI.
 */
async function updatePlotLorebook(outlineContent) {
    if (!outlineContent) {
        plotLogger.warn("没有提供剧情大纲内容，跳过世界书更新");
        return;
    }

    try {
        // Step 1: 获取当前角色卡的主世界书
        plotLogger.info("正在获取当前角色卡的主世界书...");
        
        if (!TavernHelper || typeof TavernHelper.getCurrentCharPrimaryLorebook !== 'function') {
            throw new Error("TavernHelper API 不可用，无法获取角色卡世界书");
        }
        
        const LOREBOOK_NAME = await TavernHelper.getCurrentCharPrimaryLorebook();
        
        if (!LOREBOOK_NAME) {
            throw new Error("当前角色没有绑定世界书，请先为角色卡设置主世界书");
        }
        
        plotLogger.info(`找到角色卡主世界书: ${LOREBOOK_NAME}`);

        // Step 2: Load the lorebook data
        plotLogger.info(`正在加载角色卡世界书"${LOREBOOK_NAME}"...`);
        const bookData = await loadWorldInfo(LOREBOOK_NAME);
        if (!bookData) {
            throw new Error(`无法加载世界书"${LOREBOOK_NAME}"`);
        }
        
        const entriesCount = Object.keys(bookData.entries || {}).length;
        plotLogger.info(`世界书加载成功，当前条目数: ${entriesCount}`);
        plotLogger.debug('bookData结构', {
            hasEntries: !!bookData.entries,
            entriesType: typeof bookData.entries,
            entriesKeys: bookData.entries ? Object.keys(bookData.entries) : []
        });

        // Step 3: Check if our entry already exists
        const existingEntry = Object.values(bookData.entries || {}).find(
            entry => entry.comment && entry.comment.startsWith(ENTRY_COMMENT) && !entry.disable
        );
        
        if (existingEntry) {
            plotLogger.info(`找到现有条目 (uid: ${existingEntry.uid})，正在更新...`);
            existingEntry.content = outlineContent;
            existingEntry.comment = `${ENTRY_COMMENT} - ${new Date().toISOString()}`;
            // 确保条目被启用
            existingEntry.disable = false;
            existingEntry.enabled = true;
            // 确保有触发关键词
            if (!existingEntry.key || existingEntry.key.length === 0) {
                existingEntry.key = ["剧情", "plot", "大纲", "故事", "情节"];
            }
            // 确保是常驻条目
            existingEntry.constant = true;
            plotLogger.success(`条目更新完成并已启用`);
        } else {
            plotLogger.info(`未找到现有条目，正在创建新条目...`);
            const newEntry = createWorldInfoEntry(LOREBOOK_NAME, bookData);
            
            plotLogger.debug(`createWorldInfoEntry返回的条目uid: ${newEntry.uid}`);
            
            Object.assign(newEntry, {
                comment: `${ENTRY_COMMENT} - ${new Date().toISOString()}`,
                content: outlineContent,
                key: ["剧情", "plot", "大纲", "故事", "情节"],
                constant: true,
                selectiveLogic: 0,
                position: 0,
                depth: 1,
                disable: false,
                order: 100,
                probability: 100,
            });
            
            // Ensure the entry is in bookData.entries (some SillyTavern versions may need this)
            if (bookData.entries && !bookData.entries[newEntry.uid]) {
                plotLogger.warn(`条目未自动添加到entries，手动添加 (uid: ${newEntry.uid})`);
                bookData.entries[newEntry.uid] = newEntry;
            } else {
                plotLogger.info(`条目已在entries中 (uid: ${newEntry.uid})`);
            }
            
            const newEntriesCount = Object.keys(bookData.entries || {}).length;
            plotLogger.success(`新条目创建完成，当前总条目数: ${newEntriesCount}`);
        }

        // Step 4: Save the lorebook
        plotLogger.info(`正在保存世界书...`);
        await saveWorldInfo(LOREBOOK_NAME, bookData, true);
        plotLogger.success(`剧情大纲已成功写入世界书！`);
        
        // Step 5: Force UI refresh
        plotLogger.info(`正在刷新世界书UI...`);
        if (typeof eventSource !== 'undefined' && eventSource && typeof eventSource.emit === 'function') {
            // 触发多个事件确保UI更新
            if (event_types.WORLDINFO_UPDATED) {
                eventSource.emit(event_types.WORLDINFO_UPDATED, LOREBOOK_NAME);
            }
            if (event_types.WORLDINFO_SETTINGS_UPDATED) {
                eventSource.emit(event_types.WORLDINFO_SETTINGS_UPDATED);
            }
            // 重新加载角色页面以刷新世界书列表
            if (event_types.CHARACTER_PAGE_LOADED) {
                eventSource.emit(event_types.CHARACTER_PAGE_LOADED);
            }
            plotLogger.info(`UI刷新信号已发送`);
        }

    } catch (error) {
        plotLogger.error("更新世界书失败", error);
        throw error;
    }
}

/**
 * Calls the external AI to generate a plot outline.
 * @param {object} settings - The extension settings containing API info.
 * @param {string} prompt - The fully constructed prompt.
 * @returns {Promise<string|null>} The generated plot outline or null on failure.
 */
async function callPlotGenerationAPI(settings, prompt) {
    if (!settings.apiUrl || !settings.apiKey || !settings.model) {
        apiLogger.error("API配置不完整，无法生成剧情", {
            hasUrl: !!settings.apiUrl,
            hasKey: !!settings.apiKey,
            hasModel: !!settings.model
        });
        return null;
    }

    // Limit max_tokens to avoid API errors (Gemini max is 65536)
    let maxTokens = parseInt(settings.maxTokens) || 4000;
    const MAX_ALLOWED_TOKENS = 65536;
    if (maxTokens > MAX_ALLOWED_TOKENS) {
        apiLogger.warn(`max_tokens ${maxTokens} 超出限制，将限制为 ${MAX_ALLOWED_TOKENS}`);
        maxTokens = MAX_ALLOWED_TOKENS;
    }

    const body = {
        model: settings.model,
        messages: [
            { role: 'system', content: settings.plotMasterPrompt },
            { role: 'user', content: prompt }
        ],
        temperature: parseFloat(settings.temperature) || 0.7,
        max_tokens: maxTokens,
        top_p: parseFloat(settings.topP) || 1.0,
        presence_penalty: parseFloat(settings.presencePenalty) || 0,
        frequency_penalty: parseFloat(settings.frequencyPenalty) || 0,
        stream: false,
    };

    // Ensure API URL ends with /chat/completions
    let apiUrl = settings.apiUrl.replace(/\/$/, '');
    if (!apiUrl.endsWith('/chat/completions')) {
        apiUrl += '/chat/completions';
    }
    
    apiLogger.info(`正在调用API: ${apiUrl}`);
    apiLogger.debug(`请求参数`, { model: settings.model, maxTokens, temperature: body.temperature });

    try {
        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${settings.apiKey}`,
            },
            body: JSON.stringify(body),
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`HTTP ${response.status}: ${errorText}`);
        }

        const data = await response.json();
        const content = data.choices[0]?.message?.content;
        
        if (content) {
            apiLogger.success(`API调用成功，生成内容长度: ${content.length} 字符`);
        } else {
            apiLogger.warn("API返回成功但内容为空");
        }
        
        return content;

    } catch (error) {
        apiLogger.error("API调用失败", error.message);
        return null;
    }
}


/**
 * Main function to trigger the plot generation and update cycle.
 */
export async function runPlotGenerationCycle() {
    plotLogger.info("========== 开始剧情生成周期 ==========");
    const settings = getSettings();

    if (!settings.enabled) {
        plotLogger.warn("引擎未启用，跳过生成周期");
        return;
    }

    try {
        // 1. Get the full context
        plotLogger.info("步骤 1/4: 正在收集世界状态信息...");
        const worldState = await getAllContext();
        plotLogger.info(`世界状态收集完成，总长度: ${worldState.length} 字符`);

        // 2. Build the prompt
        plotLogger.info("步骤 2/4: 正在构建提示词...");
        const prompt = `Analyze the following world state and generate a plot outline.\n${worldState}`;
        plotLogger.debug(`提示词长度: ${prompt.length} 字符`);

        // 3. Call the plot generation AI
        plotLogger.info("步骤 3/4: 正在调用AI生成剧情大纲...");
        const plotOutline = await callPlotGenerationAPI(settings, prompt);

        // 4. Update the lorebook with the new outline
        plotLogger.info("步骤 4/4: 正在更新世界书...");
        if (plotOutline) {
            await updatePlotLorebook(plotOutline);
            toastr.success("剧情大纲已成功生成并更新到世界书！", "自动剧情引擎");
            plotLogger.success("========== 剧情生成周期完成 ==========");
        } else {
            toastr.error("剧情大纲生成失败，API 未返回有效内容。", "自动剧情引擎");
            plotLogger.error("剧情生成失败：API未返回内容");
        }
    } catch (error) {
        plotLogger.error("剧情生成周期发生错误", error.message);
        toastr.error(`剧情生成失败: ${error.message}`, "自动剧情引擎");
    }
}

/**
 * Fetches the list of available models from the API endpoint.
 * This logic is adapted from a known working implementation to ensure correctness.
 * @param {object} settings - The extension settings containing API info.
 * @returns {Promise<Array<string>|null>} A list of model names, or null on failure.
 */
export async function fetchModels(settings) {
    const { apiUrl, apiKey } = settings;

    if (!apiUrl) {
        toastr.error('API URL 未配置，无法获取模型列表。', '配置错误');
        return null;
    }

    try {
        let headers = { 'Authorization': `Bearer ${apiKey}` };
        let modelsUrl = apiUrl.replace(/\/$/, ''); // Remove trailing slash

        // Correctly determine the /models endpoint from the base URL
        if (modelsUrl.endsWith('/chat/completions')) {
            modelsUrl = modelsUrl.replace(/\/chat\/completions$/, '/models');
        } else if (!modelsUrl.endsWith('/models')) {
            modelsUrl += '/models';
        }

        console.log(`[AutoPlotEngine] Fetching models from: ${modelsUrl}`);
        const response = await fetch(modelsUrl, { method: 'GET', headers });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`HTTP ${response.status}: ${errorText}`);
        }

        const jsonResponse = await response.json();
        const models = jsonResponse.data || [];

        if (!Array.isArray(models)) {
            throw new Error('API未返回有效的模型列表数组。');
        }

        const sortedModels = models.map(m => m.id).sort();
        toastr.success(`成功获取 ${sortedModels.length} 个模型`, '操作成功');
        return sortedModels;

    } catch (error) {
        console.error(`[AutoPlotEngine] 获取模型列表时发生网络或解析错误:`, error);
        toastr.error(`获取模型列表失败: ${error.message}`, 'API错误');
        return null;
    }
}
